import { ADRPackage } from '@/lib/types'

export const SAMPLE_ADR_PACKAGE: ADRPackage = {
  repoName: 'django/django',
  indexContent: `# Architecture Decision Records

This directory contains Architecture Decision Records (ADRs) for the Django project.

## ADR Index

| ADR | Title | Status | Date |
|-----|-------|--------|------|
| [0001](0001-redis-sessions.md) | Use Redis for session storage instead of database sessions | Accepted | ~2019 |
| [0002](0002-list-based-middleware.md) | Use list-based middleware ordering instead of decorator composition | Accepted | ~2012 |

---

Generated by ADR Archaeologist  
Total decisions: 8  
Archaeology discoveries: 2  
Analysis time: 463s
`,
  adrs: [
    {
      id: 'adr-001',
      title: 'Use Redis for session storage instead of database sessions',
      status: 'accepted',
      date: '2024-01-15',
      category: 'Infrastructure',
      confidence: 94,
      inferredDate: '~2019',
      context: "Django's default database-backed sessions create a read on every authenticated request. At the traffic scale evident in the performance test configuration (~400 concurrent sessions), this creates a measurable bottleneck in the hot request path handling authenticated users.",
      decision: "Store sessions in Redis with a 24-hour TTL using the redis_sessions backend. This replaces django.contrib.sessions.backends.db. Session data is serialised as JSON rather than pickle for security.",
      consequences: {
        positive: [
          'Eliminates one DB read from every authenticated request',
          'Session reads are O(1) from memory rather than O(log n) from database index',
        ],
        negative: [
          'Session data is not durable across Redis restarts — acceptable given the stateless design philosophy',
          'Adds Redis as an operational dependency',
        ],
      },
      alternatives: [
        {
          option: 'Cookie-based sessions (django.contrib.sessions.backends.signed_cookies)',
          reason: '4KB cookie size limit is too restrictive for the session data volume observed in tests',
        },
        {
          option: 'Memcached sessions',
          reason: 'No per-session TTL control — Redis was chosen for expiry granularity and richer data structure support',
        },
      ],
      archaeology: null,
      evidenceFiles: [
        'django/conf/global_settings.py',
        'requirements/base.txt',
        'tests/sessions/tests.py',
      ],
      filename: '0001-redis-sessions.md',
      markdownContent: `# Use Redis for session storage instead of database sessions

**Status:** Accepted  
**Date:** ~2019  
**Category:** Infrastructure  
**Confidence:** 94%

## Context

Django's default database-backed sessions create a read on every authenticated request. At the traffic scale evident in the performance test configuration (~400 concurrent sessions), this creates a measurable bottleneck in the hot request path handling authenticated users.

## Decision

Store sessions in Redis with a 24-hour TTL using the redis_sessions backend. This replaces django.contrib.sessions.backends.db. Session data is serialised as JSON rather than pickle for security.

## Consequences

### Positive

- Eliminates one DB read from every authenticated request
- Session reads are O(1) from memory rather than O(log n) from database index

### Negative

- Session data is not durable across Redis restarts — acceptable given the stateless design philosophy
- Adds Redis as an operational dependency

## Alternatives Considered

- **Cookie-based sessions (django.contrib.sessions.backends.signed_cookies)**: 4KB cookie size limit is too restrictive for the session data volume observed in tests
- **Memcached sessions**: No per-session TTL control — Redis was chosen for expiry granularity and richer data structure support

## Evidence Trail

- django/conf/global_settings.py
- requirements/base.txt
- tests/sessions/tests.py
`,
    },
    {
      id: 'adr-002',
      title: 'Use list-based middleware ordering instead of decorator composition',
      status: 'accepted',
      date: '2024-01-15',
      category: 'Structure',
      confidence: 88,
      inferredDate: '~2012',
      context: "Django's request/response pipeline requires ordered processing through cross-cutting concerns including auth, sessions, CSRF, and security headers. The ordering of these concerns is critical to correctness and must be visible, configurable, and debuggable per deployment environment.",
      decision: 'Use an explicit ordered list in the MIDDLEWARE setting. Each middleware class receives both request and response phases with clear positional semantics. Ordering is declarative and auditable in settings files.',
      consequences: {
        positive: [
          'Middleware ordering is explicit and visible in configuration',
          'Easy to debug — position in list equals position in the pipeline',
          'Configurable per deployment environment without code changes',
        ],
        negative: [
          'Less composable than decorator patterns',
          'Order errors produce subtle, non-obvious bugs that are difficult to trace',
        ],
      },
      alternatives: [
        {
          option: 'Decorator-based composition',
          reason: 'Implicit ordering caused conflicts in testing that were invisible until runtime — abandoned after prototyping',
        },
      ],
      archaeology: [
        {
          option: 'Decorator-based middleware',
          evidenceFile: 'django/middleware/legacy/',
          evidenceType: 'commented_out',
          rejectionReason: 'Implicit ordering made debugging request pipelines nearly impossible — order conflicts were invisible until runtime and produced misleading error traces',
        },
      ],
      evidenceFiles: [
        'django/core/handlers/base.py',
        'django/conf/global_settings.py',
        'django/middleware/legacy/',
      ],
      filename: '0002-list-based-middleware.md',
      markdownContent: `# Use list-based middleware ordering instead of decorator composition

**Status:** Accepted  
**Date:** ~2012  
**Category:** Structure  
**Confidence:** 88%

## Context

Django's request/response pipeline requires ordered processing through cross-cutting concerns including auth, sessions, CSRF, and security headers. The ordering of these concerns is critical to correctness and must be visible, configurable, and debuggable per deployment environment.

## Decision

Use an explicit ordered list in the MIDDLEWARE setting. Each middleware class receives both request and response phases with clear positional semantics. Ordering is declarative and auditable in settings files.

## Consequences

### Positive

- Middleware ordering is explicit and visible in configuration
- Easy to debug — position in list equals position in the pipeline
- Configurable per deployment environment without code changes

### Negative

- Less composable than decorator patterns
- Order errors produce subtle, non-obvious bugs that are difficult to trace

## Alternatives Considered

- **Decorator-based composition**: Implicit ordering caused conflicts in testing that were invisible until runtime — abandoned after prototyping

## Archaeology

🏛️ **Rejected Alternative Discovered**

**Decorator-based middleware**  
Evidence: \`django/middleware/legacy/\` (commented_out)  
Reason: Implicit ordering made debugging request pipelines nearly impossible — order conflicts were invisible until runtime and produced misleading error traces

## Evidence Trail

- django/core/handlers/base.py
- django/conf/global_settings.py
- django/middleware/legacy/
`,
    },
  ],
  repoUrl: 'https://github.com/django/django',
  totalDecisions: 8,
  archaeologyCount: 2,
  totalTimeMs: 463000,
}


